### ISSUE TITLE
UUID

### ISSUE THREAD

**Issue by wiched** [mdbooth/libldm#3]
I use RHEL 7
When i do ./autogen.sh
I get error:configure: error: Package requirements (uuid >= 2.21.0) were not met:
No package 'uuid' found
Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

I installed every uuid library on RHEL in the repo.

**Comment by arijitAD** [comment]
Check out Pull Request. Solution has been provided there.
https://github.com/mdbooth/libldm/pull/2

**Comment by rwmjones** [comment]
I believe this is fixed by commit 4fe96032b874c1cd12482cbb23de21297314a44d.
