### ISSUE TITLE
Error building libldm  with clang

### ISSUE THREAD

**Issue by slacka** [mdbooth/libldm#4]
Building libldm  with clang results in:
`ldmtool.c:90:25: error: duplicate 'const' declaration specifier`

Full log:
http://clang.debian.net/logs/2016-08-30/libldm_0.2.3-4_unstable_clang.log

**Comment by rwmjones** [comment]
This should be fixed by commit 2c3cc76ea6348bc92dd24e54e4609b0bf2476fa9.
